name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - cartopy
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - cython
  - xarray
  - metpy
  - pyshp
  - arm_pyart